### ISSUE TITLE
Allow middleware for oob endpoints

### ISSUE THREAD

**Issue by joscha** [topliceanu/mortimer#4]
Is there a possibility to prevent certain reads/writes to certain endpoints based on the request?
E.g. how would one intercept a call to
`mortimer.router(Book).bind(app);`
?

**Comment by topliceanu** [comment]
Hi @joscha,

I've launched a new version of mortimer! It should now address your concerns about extendibility!
It's extracted from a production environment I've been running continuously for the past two years. It now has code coverage, generated documentation, running examples, and more..
Please, please let me know what you think!

Thank  you!
